[package]
name = "ncht-manager"
version = "0.1.0"
authors = ["haryu703"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.2"
itertools = "0.10.0"
chrono = "0.4.19"
serde = "1.0.123"
serde_json = "1.0.61"
lazy_static = "1.4.0"
dotenv = "0.15.0"
anyhow = "1.0.39"
tokio = { version = "1.0", features = ["rt-multi-thread"] }
